name: "docker-build-push" 

on:
  release:
    types: 
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      # this sets up QEMU which enables multi-arch support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # this sets up buildx for multiarch support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # this step logs in into dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # This step builds, tags and push the image to dockerhub with multiarch support
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lnzap/lnd:latest
            lnzap/lnd:${{ github.ref }}
            lnzap/lnd:${{ github.ref }}-alpine
            lnzap/lnd:${{ github.ref }}-alpine3.12

      # This step outputs the image digest 
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # This step updates the dockerhub image readme with the one in the docs directory
      - name: Update docker description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: "lnd + lncli + lndconnect"
          repository: LN-Zap/docker-lnd
          readme-filepath: ./docs/DOCKERHUB-IMAGE-README.md