name: "docker-build-push" 

on:
  release:
    types: 
      - "published"
  push: 
    branches:
      - "feature/docker-build-push-action"

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
      # checkout the code (git clone with fetch-dept=1)
      - name: Checkout Code
        uses: actions/checkout@master
      
      # set the environment variable with the name of the release tag
      - name: Set env
        run: echo `RELEASE_TAG=$(echo ${{ github.ref }} | awk -F ' ' '{print $3}')` >> $GITHUB_ENV

      # builds the image
      - name: Build image
        run: docker build -t lnzap/lnd:${{ env.RELEASE_TAG }} .

      # builds the debug image
      - name: Build debug image
        run: docker build -t lnzap/lnd:${{ env.RELEASE_TAG }}-debug -f debug.Dockerfile .

      # Smoke test for the recently built image
      #- name: Image Smoke Test (regular)
      #  run:  ./.github/scripts/smoke-test.sh ${{ env.RELEASE_TAG }} $(docker run lnzap/lnd:ci-test lncli --version | awk -F ' ' '{print $3}')

      # Smoke test for the recently built debug image
      #- name: Image Smoke Test (debug)
      #  run:  ./.github/scripts/smoke-test.sh ${{ env.RELEASE_TAG }} $(docker run lnzap/lnd:debug-ci-test lncli --version | awk -F ' ' '{print $3}')

      # login to dockerhub
      - name: Dockerhub login
        run: "docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}"
      
      # Push images to Dockerhub
      - name: Push image to Dockerhub
        run: |
          docker push lnzap/lnd:${{ env.RELEASE_TAG }}
          docker push lnzap/lnd:${{ env.RELEASE_TAG }}-debug

      # This step updates the dockerhub image readme with the one in the docs directory
      #- name: Update docker description
      #  uses: peter-evans/dockerhub-description@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    short-description: "lnd + lncli + lndconnect"
      #    repository: lnzap/lnd
      #    readme-filepath: "./docs/DOCKERHUB-IMAGE-README.md"