name: "docker-build-push" 

on:
  release:
    types: 
      - "published"
  push: 
    branches:
      - "feature/docker-build-push-action"

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
      
      # This step builds, tags and push the image to dockerhub with multiarch support
      - name: "Build and push"
        run: docker build -t lnzap/lnd:ci-test .   

      # Smoke test for the recently pushed images
      - name: "Smoke Test latest"
        run: "docker run lnzap/lnd:ci-test sh lncli --version"

      # Smoke test for the recently pushed images
      - name: "Smoke Test latest"
        run: "docker push lnzap/lnd:ci-test --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}"

      # This step updates the dockerhub image readme with the one in the docs directory
      - name: "Update docker description"
        uses: "peter-evans/dockerhub-description@v2"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: "lnd + lncli + lndconnect"
          repository: "lnzap/lnd"
          readme-filepath: "./docs/DOCKERHUB-IMAGE-README.md"