name: "docker-build-push" 

on:
  release:
    types: 
      - "published"
  push: 
    branches:
      - "feature/docker-build-push-action"

  workflow_dispatch:
    inputs:
      
      docker_organization:
        description: 'the name of the docker organization'
        required: true
        default: 'lnzap'

      image_name:
        description: 'Name of the image. Should be specified with neither organization name nor tags.'
        required: true
        default: 'lnd'
      
      image_tag:
        description: 'Image tag to set for the built image.'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
      # checkout the code (git clone with fetch-dept=1)
      - name: Checkout Code
        uses: actions/checkout@master

      # This step builds, tags and push the image to dockerhub with multiarch support
      - name: Build image
        run: docker build -t lnzap/lnzap:ci-test .

      # Smoke test for the recently pushed images
      - name: Image Smoke Test 
        run: docker run lnzap/lnzap:ci-test lncli --version | awk -F ' ' '{print $3}'

      # Smoke test for the recently pushed images
      - name: Dockerhub login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
      
      # Push image to Dockerhub
      - name: Push image to Dockerhub
        run: docker push lnzap/lnzap:ci-test

      # This step updates the dockerhub image readme with the one in the docs directory
      - name: Update docker description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: "lnd + lncli + lndconnect"
          repository: lnzap/lnd
          readme-filepath: "./docs/DOCKERHUB-IMAGE-README.md"