name: "docker-build-push" 

on:
  release:
    types: 
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      # this sets up QEMU which enables emulation for multi-platform support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # this sets up buildx for multiarch support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # this step logs in into dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # This step builds, tags and push the image to dockerhub with multiarch support
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lnzap/lnd:latest
            lnzap/lnd:${{ github.ref }}
            lnzap/lnd:${{ github.ref }}-alpine
            lnzap/lnd:${{ github.ref }}-alpine3.12

      # This step builds, tags and push the debug versions of the image to dockerhub with multiarch support
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: debug.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            lnzap/lnd:latest-debug
            lnzap/lnd:${{ github.ref }}-debug
            lnzap/lnd:${{ github.ref }}-alpine-debug
            lnzap/lnd:${{ github.ref }}-alpine3.12-debug

      # Smoke test for the recently pushed debug images
      - name: Inspect
        run: docker run lnzap/lnd:latest-debug sh lncli --version

      # Smoke test for the recently pushed images
      - name: Inspect
        run: docker run lnzap/lnd:latest sh lncli --version

      # This step updates the dockerhub image readme with the one in the docs directory
      - name: Update docker description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: "lnd + lncli + lndconnect"
          repository: LN-Zap/docker-lnd
          readme-filepath: ./docs/DOCKERHUB-IMAGE-README.md